// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20230708231649_createdDBAndSeededData")]
    partial class createdDBAndSeededData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductBrandId");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is the description for a nice Hp Envy Laptop. Check it out of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.",
                            Name = "Hp Envy Laptop",
                            PictureUrl = "Images/Products/lap8.jpg",
                            Price = 109m,
                            ProductBrandId = 3,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 2,
                            Description = "Add a touch of elegance to your dining room with this modern dining table. It features a sleek design and high-quality materials.",
                            Name = "Modern Dining Table",
                            PictureUrl = "Images/Products/table1.jpg",
                            Price = 299m,
                            ProductBrandId = 6,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "The Dell XPS 15 is a powerful laptop that combines performance and portability. It features a stunning display and top-notch hardware.",
                            Name = "Dell XPS 15",
                            PictureUrl = "Images/Products/lap19.jpg",
                            Price = 1499m,
                            ProductBrandId = 3,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Samsung Galaxy S21 is a flagship smartphone with an impressive camera, powerful performance, and a stunning display.",
                            Name = "Samsung Galaxy S21",
                            PictureUrl = "Images/Products/phone1.jpg",
                            Price = 899m,
                            ProductBrandId = 3,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Achieve optimal comfort and productivity with the ErgoFlex Chair. Its ergonomic design promotes good posture and reduces back strain.",
                            Name = "ErgoFlex Chair",
                            PictureUrl = "Images/Products/chair2.jpg",
                            Price = 129m,
                            ProductBrandId = 1,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Description = "This versatile coffee table can easily transform into a dining table. It's perfect for small spaces and multi-functional use.",
                            Name = "Convertible Coffee Table",
                            PictureUrl = "Images/Products/table2.jpg",
                            Price = 199m,
                            ProductBrandId = 4,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "The Lenovo ThinkPad X1 Carbon is a lightweight and durable laptop that offers exceptional performance and long battery life.",
                            Name = "Lenovo ThinkPad X1 Carbon",
                            PictureUrl = "Images/Products/lap10.jpg",
                            Price = 1799m,
                            ProductBrandId = 2,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 8,
                            Description = "The iPhone 13 Pro is Apple's latest flagship smartphone. It boasts a powerful A15 Bionic chip, advanced camera system, and a stunning Super Retina XDR display.",
                            Name = "iPhone 13 Pro",
                            PictureUrl = "Images/Products/phone6.jpg",
                            Price = 1299m,
                            ProductBrandId = 5,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Stay cool and comfortable while working with this breathable mesh office chair. It features adjustable armrests and a supportive backrest.",
                            Name = "Mesh Office Chair",
                            PictureUrl = "Images/Products/chair3.jpg",
                            Price = 79m,
                            ProductBrandId = 6,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 10,
                            Description = "Create a charming dining space with this rustic farmhouse table. Its distressed finish and sturdy construction add character to any room.",
                            Name = "Rustic Farmhouse Table",
                            PictureUrl = "Images/Products/table12.jpg",
                            Price = 349m,
                            ProductBrandId = 1,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "The HP Spectre x360 is a versatile 2-in-1 laptop that combines elegance and performance. It features a stunning OLED display and long battery life.",
                            Name = "HP Spectre x360",
                            PictureUrl = "Images/Products/lap3.jpg",
                            Price = 1299m,
                            ProductBrandId = 1,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 12,
                            Description = "The Google Pixel 6 is a flagship smartphone powered by Google's advanced AI technology. It offers a fantastic camera system and a clean Android experience.",
                            Name = "Google Pixel 6",
                            PictureUrl = "Images/Products/phone3.jpg",
                            Price = 799m,
                            ProductBrandId = 3,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Description = "Make a statement with this executive leather chair. Its luxurious design and ergonomic features provide both style and comfort.",
                            Name = "Executive Leather Chair",
                            PictureUrl = "Images/Products/chair4.jpg",
                            Price = 249m,
                            ProductBrandId = 2,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 14,
                            Description = "Enhance your entryway or living room with this elegant glass console table. Its sleek design and tempered glass top create a contemporary look.",
                            Name = "Glass Console Table",
                            PictureUrl = "Images/Products/table4.jpg",
                            Price = 179m,
                            ProductBrandId = 4,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "The ASUS ROG Zephyrus G14 is a gaming laptop that offers a perfect balance of power and portability. It features a high-refresh-rate display and a powerful GPU.",
                            Name = "ASUS ROG Zephyrus G14",
                            PictureUrl = "Images/Products/lap4.jpg",
                            Price = 1599m,
                            ProductBrandId = 2,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 16,
                            Description = "The Sony Xperia 1 III is a flagship smartphone designed for photography enthusiasts. It features a professional-grade camera system and a stunning 4K OLED display.",
                            Name = "Sony Xperia 1 III",
                            PictureUrl = "Images/Products/phone4.jpg",
                            Price = 1199m,
                            ProductBrandId = 4,
                            ProductTypeId = 3
                        },
                        new
                        {
                            Id = 17,
                            Description = "Immerse yourself in gaming with this comfortable rocker chair. It features built-in speakers and a sleek design that enhances your gaming experience.",
                            Name = "Gaming Rocker Chair",
                            PictureUrl = "Images/Products/chair5.jpg",
                            Price = 149m,
                            ProductBrandId = 5,
                            ProductTypeId = 1
                        },
                        new
                        {
                            Id = 18,
                            Description = "Stay active and productive with this adjustable standing desk. It allows you to switch between sitting and standing positions for improved comfort.",
                            Name = "Adjustable Standing Desk",
                            PictureUrl = "Images/Products/table5.jpg",
                            Price = 299m,
                            ProductBrandId = 6,
                            ProductTypeId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "The Microsoft Surface Laptop 4 combines elegance and performance in a lightweight design. It features a vibrant touchscreen display and long battery life.",
                            Name = "Microsoft Surface Laptop 4",
                            PictureUrl = "Images/Products/lap5.jpg",
                            Price = 1299m,
                            ProductBrandId = 5,
                            ProductTypeId = 4
                        },
                        new
                        {
                            Id = 20,
                            Description = "The OnePlus 9 Pro is a high-performance smartphone that delivers a smooth and fast user experience. It features a Hasselblad camera system for stunning photos.",
                            Name = "OnePlus 9 Pro",
                            PictureUrl = "Images/Products/phone5.jpg",
                            Price = 899m,
                            ProductBrandId = 2,
                            ProductTypeId = 3
                        });
                });

            modelBuilder.Entity("Core.Entities.ProductBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alibaba"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shopify"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Apple"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Zara"
                        });
                });

            modelBuilder.Entity("Core.Entities.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Chairs"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tables"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Phones"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Laptops"
                        });
                });

            modelBuilder.Entity("Core.Entities.Product", b =>
                {
                    b.HasOne("Core.Entities.ProductBrand", "ProductBrand")
                        .WithMany()
                        .HasForeignKey("ProductBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductBrand");

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
